### ISSUE TITLE
Suggestion: Buffing estus flasks

### ISSUE THREAD

**Issue by Aer-ink** [Wehavecookies56/Bonfires#16]
estus flasks seems useles and expensive atm since you can just get some steaks instead, a buff could come handy to them to make them a more viable option I would suggest cutting to half the comsumtion time and maybe a short regen buff?

**Comment by Tow3r** [comment]
But that would make the game easier only hardcore Minecrafters use estus flasks 😎

**Comment by Wehavecookies56** [comment]
In the new version Estus Flasks will be reinforce-able using Undead Bone Shards which will increase the amount they heal. Also I feel like they're fairly powerful since they can be refilled for free and instantly at any bonfire, that being said, giving regen might be a good idea.
