### ISSUE TITLE
Config options for mod packs

### ISSUE THREAD

**Issue by plunginghornets** [Wehavecookies56/Bonfires#18]
I am very excited about the update you just released. You have no idea.

But the crafting methods for UBS and titanite are too easy for the pack I'm making. Could you implement a config to disable the default crafting (blowing up a bonfire and obsidian next to lava)? That way pack developers who want to use the mod can set their own recipe.

**Comment by Wehavecookies56** [comment]
Yep I will definitely add that, not sure why I didn't think to do that in the first place. I will probably add an option to disable reinforcing as well and a item blacklist for tools/weapons that can be reinforced.

**Comment by plunginghornets** [comment]
More than I would even dare to ask for. Thank you!
