### ISSUE TITLE
NoSuchMethodError with 1.2.1

### ISSUE THREAD

**Issue by plunginghornets** [Wehavecookies56/Bonfires#20]
Tried with my full modlist and a fresh instance with only 2 other mods. Same error after repeated attempts. Also just tried with a new instance with no other mods. Same error.

Minecraft 1.12.2
Forge 14.23.3.2655
Bonfires 1.2.1

https://pastebin.com/zDq7br6r

**Comment by plunginghornets** [comment]
Dang. Updating to the latest version is the only way Bonfires will load. But it also breaks a bunch of other mods. But that's not your problem to fix. Thanks.

**Comment by Wehavecookies56** [comment]
Try using forge 2694, I dunno if the mods you're using are still gonna be broken but that should be the oldest version it loads on

**Comment by plunginghornets** [comment]
It was actually just a few mods from Blood and Bones gaming. I spotted the name in the error and updated that mod. Everything works. Have I mentioned how thankful I am for all your help and work?

**Comment by Wehavecookies56** [comment]
Well now you have, you're welcome :) Good to hear it's working. I guess I should probably mention that it requires forge 2694+ on the curseforge page
