### ISSUE TITLE
Reinforcing doesn't use up the right items

### ISSUE THREAD

**Issue by Efimero** [Wehavecookies56/Bonfires#23]
Reinforcing weapons always uses up titanite shards instead of the higher level items that are required.

**Comment by 77wisher77** [comment]
to add onto this, you cant reinforce unless you have the higher level items in your inventory, for example level +10 requires a titanite slab to be physically in your inventory, but it only consumes a titanite shard to actually upgrade it.

it appears your checking for the correct titanite but then removing the wrong one

**Comment by Wehavecookies56** [comment]
This is very old now but I think this was a syncing issue between server and client. From my testing this seems to be fixed now.
