### ISSUE TITLE
Using Bonfire sets player spawn back to world's default spawn

### ISSUE THREAD

**Issue by yuyuisyuyu** [Wehavecookies56/Bonfires#25]
I am playing on a server and made a Bonfire earlier. However, upon using it and then returning to my spawn to test it, I found that it places me back at the world's default spawn instead.

I peeked into the code and I think it might be because the bonfire is setting spawn position to its own position which might be invalid? I am not sure.

**Comment by Wehavecookies56** [comment]
I believe this is now fixed, at least in 1.16
