### ISSUE TITLE
Suggestion: Config for the coil sword

### ISSUE THREAD

**Issue by zEpiixz** [Wehavecookies56/Bonfires#26]
I think that the coil sword has 14 attack damage is a little high. 

Would be nice to have a config to chage that or even turn it off and only being used in the crafting receipt.

**Comment by Wehavecookies56** [comment]
I kinda agree, in 1.16 it's now 8 but it's durability is still the same and I'd consider that fair as a trade off for high damage. If I remember correctly I had issues making tool material properties a config option due to the config loading after the items. Maybe there's a workaround.
