### ISSUE TITLE
Can´t reinforce weapons

### ISSUE THREAD

**Issue by BlacktoR34** [Wehavecookies56/Bonfires#31]
Hi! i have to say i love the mod! is pretty well implemented. but i have a problem.
when i try to use te Reinforment option in a bonfire, it doesn´t allow me to click the "reinforce" botton. it shows blacked.
![imagen_2022-10-07_024418629](https://user-images.githubusercontent.com/115208276/194476097-e1628426-86ad-4379-8a2e-d1c6319f7163.png)

**Comment by Wehavecookies56** [comment]
Wow I don't know how I didn't notice this. I was sure it was working before I released, I'll have a fix on CF soon.
