### ISSUE TITLE
Crash when weapon or armor breaks with Epic Fight Mod (incompatibility?)

### ISSUE THREAD

**Issue by 5stigma** [Wehavecookies56/Bonfires#33]
Crash server when weapon or armor breaks with Epic Fight Mod. sometimes it just kicks you out of the server.

Sometimes the server freezes and has to be restarted. the client does not have to be restarted. (No speak english :c srry)

**Comment by Wehavecookies56** [comment]
What version of Bonfires and Forge are you using? Any crash/error logs when it happens would be useful as well.

**Comment by 5stigma** [comment]
I will try to force the error once again, because the server doesn't generate a crash log, but the console shows a few code lines before freezing.

**Comment by 5stigma** [comment]
[Crash_bonfire_log_extract.txt](https://github.com/Wehavecookies56/Bonfires/files/9789887/Crash_bonfire_log_extract.txt)

I noticed that this only happens when the mobs are incensed.

**Comment by Wehavecookies56** [comment]
Ah I see, I'll have an update out soon
