### ISSUE TITLE
Bonfires are not saved when exiting the world

### ISSUE THREAD

**Issue by AgentHank** [Wehavecookies56/Bonfires#35]
Every time I leave the world and try to open it again, when I try to interact with the bonfires to teleport to another, it doesn't let me interact (no menu appears), when I break it and do it again, when I search for the other bonfires through the menu do not appear, it is becoming a very annoying problem.

Game Version: 1.19.2 Forge 43.2.3
Mod Version: 1.2.9

**Comment by Wehavecookies56** [comment]
Sorry for the late response, I haven't been able to reproduce this in all my testing, so I'm thinking it could be a mod conflict I know it's been a while but if you remember which mods you had/still have them that would be useful. Also if there are any errors in the log when it happens that would be very useful to see.
