### ISSUE TITLE
If a bonfire destory by water, it still present in the list and can be used.

### ISSUE THREAD

**Issue by linxcy** [Wehavecookies56/Bonfires#40]
Mod version: v1.2.13
Minecraft version: 1.20.1
Forge version: 47.2.1
Describe what the bug is, how to reproduce, when it happened, etc.
If a bonfire destory by water, it still present in the list and can be used.

**Comment by Wehavecookies56** [comment]
Oh weird they're not supposed to be broken by water (though I guess that kinda makes sense) must've been something in 1.20 that changed that I'll fix that soon
