### ISSUE TITLE
Mod incompatible with Mob Grinding Utils

### ISSUE THREAD

**Issue by SnowSoldier03** [Wehavecookies56/Bonfires#44]
Mod version: 1.2.15-8613d54
Mod grinding utils version: 1.0.3
Minecraft version: 1.20.1
Forge version:  47.2.18

Describe what the bug is, how to reproduce, when it happened, etc.
mobgrinder dont do damage. nobody is taking damage. 
Modlink:
https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils
(attach log file)
[latest.log](https://github.com/Wehavecookies56/Bonfires/files/13850566/latest.log)

**Comment by Wehavecookies56** [comment]
I just tested it and everything seems to be working fine, the mob grinder deals damage could it be another mod you're using? I'm not really sure how anything in Bonfires would break the functionality of that mod anyway.

**Comment by SnowSoldier03** [comment]
Yeah i just testet it also again xD. here is a for you 
sry for bad quality (only for an evidence)
https://github.com/Wehavecookies56/Bonfires/assets/67830830/931862b2-18b2-4424-9b2a-24ef1ddd8788
Ive just added jade to see lifebars
Here is also my log again
[latest.log](https://github.com/Wehavecookies56/Bonfires/files/13929053/latest.log)

**Comment by Trumpeda** [comment]
Hey!
I have the same issue. Nothing is taking damage, neither mobs nor players. Just wanted to comment to make sure its still a known issue!

**Comment by Wehavecookies56** [comment]
I've tried mob grinding utils with bonfires installed and everything is working fine have you got any other mods?

**Comment by Trumpeda** [comment]
Yes, I do, I am using the Mod in All the Mods 9. Sorry, forgot to mention!

**Comment by Wehavecookies56** [comment]
Would you be able to send a video? I've just tested it in ATM9 and as you can see here they are taking damage [https://www.youtube.com/watch?v=2czdgtgIBFc](url)

**Comment by Trumpeda** [comment]
Huh, weird. I reinstalled it, put in the bonfires mod and this is what happened: 
[](https://youtu.be/_c7h-cxsGJI)
Same thing on the newest version of the modpack, or the newest version of everything, for that matter

**Comment by Wehavecookies56** [comment]
Okay I've figured out why it's happening will have an update out soon!

**Comment by Trumpeda** [comment]
Thank you so much!

Am Sa., 11. Mai 2024 um 21:48 Uhr schrieb Toby ***@***.***>:
