### ISSUE TITLE
[request] backport some feature to 1.12

### ISSUE THREAD

**Issue by Biviho** [Wehavecookies56/Bonfires#45]
hi, sorry to bother with this kin of request, but i wantet to know if you would be interested in backporting some of the newest adition to 1.12, mainly:

- reinforcing using nbt tag instead of capability (so that it could be readable and usable by other mods)
- the ability to configure various values in the mod like damage by upgrade, number of sips by estus upgrade, number of estus upgrade

i'm asking since 1.12 is still pretty active, an if you are not interesting in backporting, i would ask if you are ok if i bring Bonfires to the 1.12 moding coalition to continue development for 1.12

**Comment by Wehavecookies56** [comment]
I'm not familiar with the modding coalition but if someone wants to update it they're welcome to. I probably could update it but I can't get the 1.12 dev environment to work anymore plus I'd rather spend the time updating to newer versions and porting to neoforge and maybe fabric.
