### ISSUE TITLE
Bonfire still appears in travel GUI after being destroyed

### ISSUE THREAD

**Issue by TriAstrus** [Wehavecookies56/Bonfires#48]
Mod version: 1.2.17
Minecraft version: 1.20.1
Forge version: 47.3.0

Im working on a sort of adventure map and somehow a bonfire got destroyed but it still shows up in the travel gui. Im honestly not sure how this happened so i dont know how to reproduce the issue.

**Comment by Wehavecookies56** [comment]
I guess it got destroyed in a way I didn't account for, I'm gonna make it check for invalid bonfires when you use a bonfire and remove any invalid ones so this shouldn't happen after then.

**Comment by Wehavecookies56** [comment]
This should now be fixed in 1.2.18
