### ISSUE TITLE
no crafting recipe for homeward bone

### ISSUE THREAD

**Issue by Pandaxolotl** [Wehavecookies56/Bonfires#49]
Mod version: v1.2.18
Minecraft version: 1.20.6
Fabric version: 0.16.0

cant craft the homeward bone even after restarting minecraft multiple times. 
![image_crafting](https://github.com/user-attachments/assets/8f4237c3-f1df-46db-99a6-4133a2798562)

even tried the /recipe command to give me the recipe and it says "No new recipes were learned"
![image_command](https://github.com/user-attachments/assets/af5db967-9b85-4b03-b87e-5cd9f3cd1621)

checked almost every changelog _(of the mod)_ and found nothing
its still in the creative inventory however

![image_inventory](https://github.com/user-attachments/assets/dea98ea2-8721-4633-a60d-3feab9e209db)

downgraded to 1.20.4 without any other mods and the recipe is there
![image_of_older_version](https://github.com/user-attachments/assets/fe97313f-d8a1-4122-9089-4694092defcb)

removed every mod except bonfire (fabric api and owolib) on 1.20.6, still not working
![image_no_mods](https://github.com/user-attachments/assets/0dada377-9473-403d-abfc-eaf850d6530e)

any way to fix this? _since otherwise i cant craft them in a survival world_

**Comment by Wehavecookies56** [comment]
Oh whoops I must've missed that when I was porting to .6 I'll fix that now

**Comment by Wehavecookies56** [comment]
Alright 1.2.18b is on modrinth now and will be on curseforge once it gets approved

**Comment by Pandaxolotl** [comment]
cant craft estus shards this time @Wehavecookies56 
![image](https://github.com/user-attachments/assets/aecccdab-abc0-41bb-9015-8027d3a02116)

**Comment by Wehavecookies56** [comment]
Damn it thought I checked every recipe, fix will be up soon
